//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERC.Repository.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class DbQueryPortal {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DbQueryPortal() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ERC.Repository.Resources.DbQueryPortal", typeof(DbQueryPortal).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to update candidate 
        ///set 
        ///	Name = @Name,
        ///	Gender = @Gender,
        ///	HomeAddress = @HomeAddress,
        ///	CurrentCityCode = @CurrentCityCode,
        ///	CurrentAddress= @CurrentAddress,
        ///	PostalCode = @PostalCode,
        ///	NPWPNo = @NPWPNo,
        ///	NPWPName = @NPWPName,
        ///	BankAccountNo = @BankAccountNo,
        ///	BankAccountName = @BankAccountName,
        ///	ChangedWhen = @ChangedWhen,
        ///	ChangedBy = @ChangedBy,
        ///	[Status] = @Status,
        ///	BirthDate = @BirthDate,
        ///	TemporaryAgentCode = @TemporaryAgentCode,
        ///	Email = @Email, 
        ///	PTKPHeader = @PTKPHeader, 
        ///	PTKPDet [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AddCandidateBasicInfo {
            get {
                return ResourceManager.GetString("AddCandidateBasicInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to update candidate 
        ///set 
        ///	Name = @Name,
        ///	Gender = @Gender,
        ///	HomeAddress = @HomeAddress,
        ///	CurrentCityCode = @CurrentCityCode,
        ///	CurrentAddress= @CurrentAddress,
        ///	PostalCode = @PostalCode,
        ///	NPWPNo = @NPWPNo,
        ///	NPWPName = @NPWPName,
        ///	BankAccountNo = @BankAccountNo,
        ///	BankAccountName = @BankAccountName,
        ///	ChangedWhen = @ChangedWhen,
        ///	ChangedBy = @ChangedBy,
        ///	[Status] = @Status,
        ///	BirthDate = @BirthDate,
        ///	TemporaryAgentCode = @TemporaryAgentCode,
        ///	Email = @Email, 
        ///	PTKPHeader = @PTKPHeader, 
        ///	PTKPDet [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AddCandidateBasicInfoMobile {
            get {
                return ResourceManager.GetString("AddCandidateBasicInfoMobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert into CandidateDependencies values (@CandidateId, @Status, @Name, @BirthDate).
        /// </summary>
        internal static string AddCandidateDependencies {
            get {
                return ResourceManager.GetString("AddCandidateDependencies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to update Candidate set SpouseName=@SpouseName, SpouseBirthDate=@SpouseBirthDate where id = @CandidateId.
        /// </summary>
        internal static string AddCandidateFamily {
            get {
                return ResourceManager.GetString("AddCandidateFamily", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to update Candidate set SpouseName=@SpouseName, SpouseBirthDate=@SpouseBirthDate where id = @CandidateId.
        /// </summary>
        internal static string AddCandidateFamilyMobile {
            get {
                return ResourceManager.GetString("AddCandidateFamilyMobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO CandidateInformasiPribadi (CandidateId, Pertanyaan1, Pertanyaan2, Pertanyaan3, Pertanyaan4)
        ///VALUES(@CandidateId, @Pertanyaan1, @Pertanyaan2, @Pertanyaan3, @Pertanyaan4).
        /// </summary>
        internal static string AddCandidateInformasiPribadi {
            get {
                return ResourceManager.GetString("AddCandidateInformasiPribadi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to insert into CandidateFile values (@CandidateId,@Type,@FileId,@CreatedBy,@CreatedWhen,@ChangedWhen,@ChangedBy).
        /// </summary>
        internal static string AddCandidateProfilePhoto {
            get {
                return ResourceManager.GetString("AddCandidateProfilePhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO CandidateProfilingAnswer(HeaderId, QuestionID, Description, Answer, Point)
        ///values(@HeaderId, @QuestionID, @Description, @Answer, @Point);
        ///SELECT CAST(SCOPE_IDENTITY() as int);.
        /// </summary>
        internal static string AddCandidateProfilingAnswer {
            get {
                return ResourceManager.GetString("AddCandidateProfilingAnswer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to insert into CandidateReference values (@CandidateId, @Name, @Organization, @Relation, @PhoneNumber, @HasKnownFor).
        /// </summary>
        internal static string AddCandidateReference {
            get {
                return ResourceManager.GetString("AddCandidateReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to insert into CandidateRelationInInsurance values (@CandidateId,@Name,@Relation, @CompanyName, @Position, @Year).
        /// </summary>
        internal static string AddCandidateRelationInInsurance {
            get {
                return ResourceManager.GetString("AddCandidateRelationInInsurance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to insert into CandidateWorkExperienceInInsurance 
        ///values (@CandidateId,@CompanyName,@LastPosition,@MainOfficeAddress,@HasBeenJoinFor,@TerminateDate,@OldAgentCode).
        /// </summary>
        internal static string AddCandidateWorkExperienceInInsurance {
            get {
                return ResourceManager.GetString("AddCandidateWorkExperienceInInsurance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to insert into Account (LoginName, Password, RoleID, TypeID, ManagerLoginName,Email, IsActive, IsDeleted, JoinDate, DisplayName, CreatedWhen, CreatedWho, ChangedWhen, ChangedWho, BirthDate, NoKTP) 
        ///Values (@LoginName, @Password,  @RoleID, @TypeID, @ManagerLoginName,@Email, @IsActive, @IsDeleted, @JoinDate, @DisplayName, @CreatedWhen, @CreatedWho, @ChangedWhen, @ChangedWho, @BirthDate, @Ktp).
        /// </summary>
        internal static string AddElearningAccount {
            get {
                return ResourceManager.GetString("AddElearningAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to insert into Candidate (RecruiterAgentCode,Level,Name, BirthDate, CityCode, Gender, PhoneNo, Profession,JoinDate,GroupLevel, IsDeleted, CreatedWhen, CreatedBy, ChangedWhen, ChangedBy,IDFromMobile)  
        ///               values (@RecruiterAgentCode,0,@Name, @BirthDate, @CityCode, @Gender, @PhoneNo, @Profession,@JoinDate,@GroupLevel,0, @CreatedWhen, @CreatedBy, @ChangedWhen, @ChangedBy,@IDFromMobile) SELECT SCOPE_IDENTITY() as int.
        /// </summary>
        internal static string AddQuickContact {
            get {
                return ResourceManager.GetString("AddQuickContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT DocumentCheckingFlag, AllLeaderApproveFlag, AajiPassedFlag, ELearningPassedFlag 
        ///FROM Candidate WHERE ID = @ID.
        /// </summary>
        internal static string CekCandidateFlag {
            get {
                return ResourceManager.GetString("CekCandidateFlag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT DocumentCheckingFlag, AllLeaderApproveFlag, AajiPassedFlag, ELearningPassedFlag 
        ///FROM Candidate WHERE TemporaryAgentCode=@TemporaryAgentCode.
        /// </summary>
        internal static string CekCandidateFlagByTempAgentCode {
            get {
                return ResourceManager.GetString("CekCandidateFlagByTempAgentCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select COUNT(ID) from DocumentCheck where CandidateId = @CandidateId and Status = &apos;NEED REVISION&apos;.
        /// </summary>
        internal static string CountDocumentCheckByCandidateId {
            get {
                return ResourceManager.GetString("CountDocumentCheckByCandidateId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete from candidatedependencies where Id = @Id.
        /// </summary>
        internal static string DeleteCandidateDependencies {
            get {
                return ResourceManager.GetString("DeleteCandidateDependencies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to delete from CandidateReference where id = @Id.
        /// </summary>
        internal static string DeleteCandidateReference {
            get {
                return ResourceManager.GetString("DeleteCandidateReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to delete from CandidateRelationInInsurance where id=@Id.
        /// </summary>
        internal static string DeleteCandidateRelationInInsurance {
            get {
                return ResourceManager.GetString("DeleteCandidateRelationInInsurance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to delete from CandidateWorkExperienceInInsurance where id = @Id.
        /// </summary>
        internal static string DeleteCandidateWorkExperienceInInsurance {
            get {
                return ResourceManager.GetString("DeleteCandidateWorkExperienceInInsurance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select top 1 Aed.AajiExamId as Id,AED.CandidateId,C.Name as CandidateName,AE.ExamDate, AED.Status,CONVERT(varchar(10), Year(ExamDate)) + &apos;/&apos; + CONVERT(varchar(10), Month(ExamDate))+ &apos;/&apos; +CONVERT(varchar(10), Day(ExamDate))  as [start],&apos;Jadwal Anda&apos; as [title], EL.Name as ExamLocationName, AE.RegisteredUser
        ///from AajiExamDetail AED
        ///left join AajiExam AE on AED.AajiExamId = AE.ID
        ///left join Candidate C on C.ID = AED.CandidateId
        ///left join ExamLocation EL on EL.ID = AE.ExamLocationId
        ///where AED.CandidateId =  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GetAajiByCandidateId {
            get {
                return ResourceManager.GetString("GetAajiByCandidateId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT top 1 AE.ID as AajiExamId,CDT.Id as CandidateId,AE.ExamDate as AajiExamDate,EL.ExamType,AED.ProductType, El.Name +&apos;. &apos;+ C.Name as ExamLocationName, EL.ID as ExamLocationId
        ///FROM AajiExamDetail AED
        ///JOIN AajiExam AE on AED.AajiExamId = AE.Id
        ///JOIN ExamLocation EL on EL.Id = AE.ExamLocationId
        ///JOIN City C on C.CityCode = EL.CityCode
        ///JOIN Candidate CDT on CDT.Id = AED.CandidateId
        ///WHERE CDT.Id = @CandidateId.
        /// </summary>
        internal static string GetAajiExamCandidate {
            get {
                return ResourceManager.GetString("GetAajiExamCandidate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT top 1 [LoginName]
        ///      ,[Password]
        ///      ,[Email]
        ///      ,[RoleID]
        ///      ,[DisplayName]
        ///      ,[AgentCode]
        ///      ,[Gender]
        ///      ,[PhoneNo]
        ///      ,[IsActive]
        ///      ,[IsDeleted]
        ///      ,[CreatedWhen]
        ///      ,[CreatedBy]
        ///      ,[ChangedWhen]
        ///      ,[ChangedBy]
        ///      ,[TeamCode]
        ///      ,[LocationCode]
        ///      ,[HiringDate]
        ///      ,[StatusEffective]
        ///  FROM [Account] WHERE AgentCode = @AgentCode.
        /// </summary>
        internal static string GetAccount {
            get {
                return ResourceManager.GetString("GetAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select AgentCode from Account where LoginName = @LoginName.
        /// </summary>
        internal static string GetAgentCodeByLoginName {
            get {
                return ResourceManager.GetString("GetAgentCodeByLoginName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT ROW_NUMBER() OVER(ORDER BY el.id) AS NUMBER,
        ///		el.Id,
        ///		el.Name,c.Id as CityId,
        ///		el.CityCode,
        ///		c.Name as CityName,
        ///		el.ExamType,
        ///		el.IsActive
        ///	FROM ExamLocation el
        ///	join City c on c.CityCode = el.CityCode
        ///	WHERE  el.IsDelete != 1.
        /// </summary>
        internal static string GetAllListExamLocation {
            get {
                return ResourceManager.GetString("GetAllListExamLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT * FROM (
        ///	SELECT ROW_NUMBER() OVER(ORDER BY a.ID) AS NUMBER,
        ///		a.ID, a.CandidateId, d.Name CandidateName, a.RecruiterCode, b.DisplayName RecruiterName,
        ///		a.ApproverCode, c.DisplayName ApproverName, a.StatusApproval, a.Reason, a.ApprovalDate, r.RoleName,
        ///		(
        ///			SELECT COUNT(*)
        ///			FROM ApprovalList a JOIN Account b ON a.RecruiterCode = b.AgentCode
        ///			JOIN Account c ON a.ApproverCode = c.AgentCode JOIN Candidate d ON a.CandidateId = d.ID
        ///			JOIN [Role] r ON c.RoleID = r.ID
        ///			WHERE a.IsActive = [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GetApprovalProgress {
            get {
                return ResourceManager.GetString("GetApprovalProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select a.ID, a.CandidateId, d.Name CandidateName, a.RecruiterCode, b.DisplayName RecruiterName,
        ///a.ApproverCode, c.DisplayName ApproverName, a.StatusApproval, a.Reason, a.ApprovalDate, r.RoleName
        ///FROM ApprovalList a JOIN Account b ON a.RecruiterCode = b.AgentCode
        ///JOIN Account c ON a.ApproverCode = c.AgentCode JOIN Candidate d ON a.CandidateId = d.ID
        ///JOIN [Role] r ON c.RoleID = r.ID
        ///WHERE a.IsActive = 1 and a.CandidateId = @CandidateId.
        /// </summary>
        internal static string GetApprovalProgressMobile {
            get {
                return ResourceManager.GetString("GetApprovalProgressMobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to declare @RecomendedPosition int = (select top 1 RecommendedPosition 
        ///from CandidateProfilingHeader 
        ///where CandidateId = @CandidateId and IsComplete = 1 and RecommendedPosition != &apos;-&apos; and RecommendedPosition !=0)
        ///
        ///declare @true bit = 1
        ///declare @false bit = 0
        ///
        ///select tbl3.*,r.RoleName as LevelName from (
        ///select T.TeamCode,T.TeamName,tbl1.*,DisplayName as RecruiterName,a.Email RecruiterMail,a.LocationCode RecruiterLocationCode, rh.HierarkiLevel, l.AgentLocation as AgencyDirector, r.RoleName as Recruite [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GetCandidate {
            get {
                return ResourceManager.GetString("GetCandidate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select id, candidateid, status, name, birthdate from candidatedependencies where CandidateId = @CandidateId.
        /// </summary>
        internal static string GetCandidateDependencies {
            get {
                return ResourceManager.GetString("GetCandidateDependencies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to declare @RecomendedPosition int = (select top 1 RecommendedPosition 
        ///from CandidateProfilingHeader 
        ///where CandidateId = @CandidateId and IsComplete = 1 and RecommendedPosition != &apos;-&apos; and RecommendedPosition !=0)
        ///print @RecomendedPosition
        ///select tbl3.*,r.RoleName as LevelName from (
        ///select T.TeamCode,T.TeamName,tbl1.*,DisplayName as RecruiterName, rh.HierarkiLevel, l.AgentLocation as AgencyDirector, r.RoleName as RecruiterPosition, ct2.Name as CurrentCityName, @RecomendedPosition as RecommendedPosition  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GetCandidateMobile {
            get {
                return ResourceManager.GetString("GetCandidateMobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --agency director digunakan ketika level hirarki kandidat di bawah level hirarki rekruiter dan menyebabkan agency director - data direct manager menggunakan data si recruiter
        ///--last update tambah tbl1.*
        ///declare @RecomendedPosition int = (select top 1 RecommendedPosition 
        ///from CandidateProfilingHeader 
        ///where CandidateId = @CandidateId and IsComplete = 1 and RecommendedPosition != &apos;-&apos; and RecommendedPosition !=0)
        ///
        ///select r.RoleName as LevelName,*, tbl1.RoleID,GroupLevel,DisplayName as RecruiterName, rh. [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GetCandidateold {
            get {
                return ResourceManager.GetString("GetCandidateold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to declare @RecomendedPosition int = (select top 1 RecommendedPosition 
        ///from CandidateProfilingHeader 
        ///where CandidateId = @CandidateId and IsComplete = 1 and RecommendedPosition != &apos;-&apos; and RecommendedPosition !=0)
        ///select tbl3.*,r.RoleName as LevelName from (
        ///select T.TeamCode,T.TeamName,tbl1.*,DisplayName as RecruiterName, rh.HierarkiLevel, l.AgentLocation as AgencyDirector, r.RoleName as RecruiterPosition, ct2.Name as CurrentCityName, @RecomendedPosition as RecommendedPosition from (
        ///select 
        ///	cdt.Id,         /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GetCandidateold2 {
            get {
                return ResourceManager.GetString("GetCandidateold2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select Id,CandidateId, [Name], Organization, Relation, PhoneNumber, HasKnownFor
        ///from CandidateReference
        ///where CandidateId=@CandidateId.
        /// </summary>
        internal static string GetCandidateReference {
            get {
                return ResourceManager.GetString("GetCandidateReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select Id, CandidateId,Name, Relation, CompanyName, Position, Year 
        ///from CandidateRelationInInsurance 
        ///where CandidateId=@CandidateId.
        /// </summary>
        internal static string GetCandidateRelationInInsurance {
            get {
                return ResourceManager.GetString("GetCandidateRelationInInsurance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select id,candidateid,companyname, lastposition, mainofficeaddress, hasbeenjoinfor,terminatedate,oldagentcode 
        ///from CandidateWorkExperienceInInsurance
        ///where candidateid=@CandidateId.
        /// </summary>
        internal static string GetCandidateWorkExperienceInInsurance {
            get {
                return ResourceManager.GetString("GetCandidateWorkExperienceInInsurance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select Id, Name, Gender, City, PhoneNo, Birthdate, Profession, case when SubmitDate IS NULL then &apos;Pengisian RF&apos; 
        ///		when AllLeaderApproveFlag = 0 then &apos;Menunggu Persetujuan&apos; 
        ///		when DocumentCheckingFlag = 0 Then &apos;Menunggu Proses Dokumen Cek&apos; 
        ///		when ElearningPassedFlag = 0 then &apos;Menunggu Hasil Elearning&apos; 
        ///		when AajiPassedFlag = 0 then &apos;Menunggu Hasil Ujian AAJI&apos;
        ///		when submitdate is not null and AllLeaderApproveFlag=1 and DocumentCheckingFlag = 1 and AajiPassedFlag = 1 then &apos;Agen Aktif&apos;
        ///		end as Statu [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GetContact {
            get {
                return ResourceManager.GetString("GetContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT * FROM (
        ///	SELECT ROW_NUMBER() OVER(ORDER BY C.ID desc) AS NUMBER,
        ///		C.ID, C.Name, C.Gender, C.City, C.PhoneNo, C.Birthdate, C.Profession, 
        ///		case when SubmitDate IS NULL then &apos;Pengisian RF&apos; 
        ///		when AllLeaderApproveFlag = 0 then &apos;Menunggu Persetujuan&apos; 
        ///		when DocumentCheckingFlag = 0 Then &apos;Menunggu Proses Dokumen Cek&apos; 
        ///		when ElearningPassedFlag = 0 then &apos;Menunggu Hasil Elearning&apos; 
        ///		when AajiPassedFlag = 0 then &apos;Menunggu Hasil Ujian AAJI&apos;
        ///		when submitdate is not null and AllLeaderApproveFlag [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GetContactAsc {
            get {
                return ResourceManager.GetString("GetContactAsc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT * FROM (
        ///	SELECT ROW_NUMBER() OVER(ORDER BY C.ID desc) AS NUMBER,
        ///		C.ID, C.Name, C.Gender, C.City, C.PhoneNo, C.Birthdate, C.Profession, 
        ///		case when SubmitDate IS NULL then &apos;Pengisian RF&apos; 
        ///		when AllLeaderApproveFlag = 0 then &apos;Menunggu Persetujuan&apos; 
        ///		when DocumentCheckingFlag = 0 Then &apos;Menunggu Proses Dokumen Cek&apos; 
        ///		when ElearningPassedFlag = 0 then &apos;Menunggu Hasil Elearning&apos; 
        ///		when AajiPassedFlag = 0 then &apos;Menunggu Hasil Ujian AAJI&apos;
        ///		when submitdate is not null and AllLeaderApproveFlag [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GetContactDesc {
            get {
                return ResourceManager.GetString("GetContactDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to exec GetContactDetail @CandidateId.
        /// </summary>
        internal static string GetContactDetail {
            get {
                return ResourceManager.GetString("GetContactDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select * from(
        ///select  Id,
        ///		JoinDate as SubmitDate, 
        ///		[Name], 
        ///		RoleName as [Level], 
        ///		case when Tbl3.ApprovalDate is null then &apos;Pengisian RF&apos; else &apos;Menunggu Approval&apos; end as StatusAgency,
        ///		AgentLocation as [Location],
        ///		Status
        ///		from(
        ///select * from (
        ///	select C.Id,[Name], R.RoleName, C.ChangedWhen, [Level], C.JoinDate, L.AgentLocation, C.Status
        ///	from Candidate C 
        ///	left join [Role] R on R.ID = [Level]
        ///	left join [Location] L on L.Id = C.Location
        ///	where C.IsDeleted != 1 
        ///) as Tbl1 left joi [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GetContactDetail2 {
            get {
                return ResourceManager.GetString("GetContactDetail2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --cari agent aktif
        ///SELECT * FROM (
        ///	SELECT ROW_NUMBER() OVER(ORDER BY C.ID desc) AS NUMBER,
        ///		C.ID, C.Name, C.Gender, C.City, C.PhoneNo, C.Birthdate, C.Profession,
        ///			case when SubmitDate IS NULL then &apos;Pengisian RF&apos; 
        ///		when AllLeaderApproveFlag = 0 then &apos;Menunggu Persetujuan&apos; 
        ///		when DocumentCheckingFlag = 0 Then &apos;Menunggu Proses Dokumen Cek&apos; 
        ///		when ElearningPassedFlag = 0 then &apos;Menunggu Hasil Elearning&apos; 
        ///		when AajiPassedFlag = 0 then &apos;Menunggu Hasil Ujian AAJI&apos;
        ///		when submitdate is not null and  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GetContactFilteredActiveAgent {
            get {
                return ResourceManager.GetString("GetContactFilteredActiveAgent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --cari pengisian rf
        ///SELECT * FROM (
        ///	SELECT ROW_NUMBER() OVER(ORDER BY C.ID desc) AS NUMBER,
        ///		C.ID, C.Name, C.Gender, C.City, C.PhoneNo, C.Birthdate, C.Profession,
        ///			case when SubmitDate IS NULL then &apos;Pengisian RF&apos; 
        ///		when AllLeaderApproveFlag = 0 then &apos;Menunggu Persetujuan&apos; 
        ///		when DocumentCheckingFlag = 0 Then &apos;Menunggu Proses Dokumen Cek&apos; 
        ///		when ElearningPassedFlag = 0 then &apos;Menunggu Hasil Elearning&apos; 
        ///		when AajiPassedFlag = 0 then &apos;Menunggu Hasil Ujian AAJI&apos;
        ///		when submitdate is not null and [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GetContactFilteredRFForm {
            get {
                return ResourceManager.GetString("GetContactFilteredRFForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --cari menunggu hasil ujian aaji
        ///SELECT * FROM (
        ///	SELECT ROW_NUMBER() OVER(ORDER BY C.ID desc) AS NUMBER,
        ///		C.ID, C.Name, C.Gender, C.City, C.PhoneNo, C.Birthdate, C.Profession,
        ///			case when SubmitDate IS NULL then &apos;Pengisian RF&apos; 
        ///		when AllLeaderApproveFlag = 0 then &apos;Menunggu Persetujuan&apos; 
        ///		when DocumentCheckingFlag = 0 Then &apos;Menunggu Proses Dokumen Cek&apos; 
        ///		when ElearningPassedFlag = 0 then &apos;Menunggu Hasil Elearning&apos; 
        ///		when AajiPassedFlag = 0 then &apos;Menunggu Hasil Ujian AAJI&apos;
        ///		when submitdate is [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GetContactFilteredWaitingAAJIExam {
            get {
                return ResourceManager.GetString("GetContactFilteredWaitingAAJIExam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --cari menunggu persetujuan
        ///SELECT * FROM (
        ///	SELECT ROW_NUMBER() OVER(ORDER BY C.ID desc) AS NUMBER,
        ///		C.ID, C.Name, C.Gender, C.City, C.PhoneNo, C.Birthdate, C.Profession,
        ///			case when SubmitDate IS NULL then &apos;Pengisian RF&apos; 
        ///		when AllLeaderApproveFlag = 0 then &apos;Menunggu Persetujuan&apos; 
        ///		when DocumentCheckingFlag = 0 Then &apos;Menunggu Proses Dokumen Cek&apos; 
        ///		when ElearningPassedFlag = 0 then &apos;Menunggu Hasil Elearning&apos; 
        ///		when AajiPassedFlag = 0 then &apos;Menunggu Hasil Ujian AAJI&apos;
        ///		when submitdate is not  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GetContactFilteredWaitingApproval {
            get {
                return ResourceManager.GetString("GetContactFilteredWaitingApproval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --cari menunggu proses document check
        ///SELECT * FROM (
        ///	SELECT ROW_NUMBER() OVER(ORDER BY C.ID desc) AS NUMBER,
        ///		C.ID, C.Name, C.Gender, C.City, C.PhoneNo, C.Birthdate, C.Profession,
        ///			case when SubmitDate IS NULL then &apos;Pengisian RF&apos; 
        ///		when AllLeaderApproveFlag = 0 then &apos;Menunggu Persetujuan&apos; 
        ///		when DocumentCheckingFlag = 0 Then &apos;Menunggu Proses Dokumen Cek&apos; 
        ///		when ElearningPassedFlag = 0 then &apos;Menunggu Hasil Elearning&apos; 
        ///		when AajiPassedFlag = 0 then &apos;Menunggu Hasil Ujian AAJI&apos;
        ///		when submitda [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GetContactFilteredWaitingDocumentCheck {
            get {
                return ResourceManager.GetString("GetContactFilteredWaitingDocumentCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --cari menunggu hasil elearning
        ///SELECT * FROM (
        ///	SELECT ROW_NUMBER() OVER(ORDER BY C.ID desc) AS NUMBER,
        ///		C.ID, C.Name, C.Gender, C.City, C.PhoneNo, C.Birthdate, C.Profession,
        ///			case when SubmitDate IS NULL then &apos;Pengisian RF&apos; 
        ///		when AllLeaderApproveFlag = 0 then &apos;Menunggu Persetujuan&apos; 
        ///		when DocumentCheckingFlag = 0 Then &apos;Menunggu Proses Dokumen Cek&apos; 
        ///		when ElearningPassedFlag = 0 then &apos;Menunggu Hasil Elearning&apos; 
        ///		when AajiPassedFlag = 0 then &apos;Menunggu Hasil Ujian AAJI&apos;
        ///		when submitdate is  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GetContactFilteredWaitingElearning {
            get {
                return ResourceManager.GetString("GetContactFilteredWaitingElearning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select Id,GroupId, GroupName
        ///from GroupLevel
        ///where GroupID in (2,3).
        /// </summary>
        internal static string GetContactListLevel {
            get {
                return ResourceManager.GetString("GetContactListLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select Id, Name, Gender, City, PhoneNo, Birthdate, Profession, case when SubmitDate IS NULL then &apos;Pengisian RF&apos; 
        ///		when AllLeaderApproveFlag = 0 then &apos;Menunggu Persetujuan&apos; 
        ///		when DocumentCheckingFlag = 0 Then &apos;Menunggu Proses Dokumen Cek&apos; 
        ///		when ElearningPassedFlag = 0 then &apos;Menunggu Hasil Elearning&apos; 
        ///		when AajiPassedFlag = 0 then &apos;Menunggu Hasil Ujian AAJI&apos;
        ///		when submitdate is not null and AllLeaderApproveFlag=1 and DocumentCheckingFlag = 1 and AajiPassedFlag = 1 then &apos;Agen Aktif&apos;
        ///		end as Statu [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GetContactMobileNew {
            get {
                return ResourceManager.GetString("GetContactMobileNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select TblSubmit.RfSubmit, TblProses.RfProses, TblActive.AgentActivated
        ///	from(
        ///		--sudah submit
        ///		select Count(id) as RfSubmit from candidate 
        ///		where SubmitDate is not NULL AND IsDeleted != 1 and Month(submitdate) = @Month and Year(submitdate) = @Year
        ///
        ///	) as TblSubmit,
        ///	(
        ///		select Count(id) as RfProses from candidate 
        ///		where  permanentagentcode is null and Status!=&apos;REJECT&apos; and IsDeleted != 1  and Month(submitdate) = @Month and Year(submitdate) = @Year 		
        ///	) as TblProses,
        ///	(
        ///		select Count(id)  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GetDashboardActivitySummaryCMS {
            get {
                return ResourceManager.GetString("GetDashboardActivitySummaryCMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select TblSubmit.RfSubmit, TblProses.RfProses, TblActive.AgentActivated
        ///	from(
        ///		--sudah submit
        ///		select Count(id) as RfSubmit from candidate 
        ///		where SubmitDate is not NULL AND IsDeleted != 1 AND RecruiterAgentCode=@RecruiterAgentCode and Month(submitdate) = @Month and Year(submitdate) = @Year
        ///
        ///	) as TblSubmit,
        ///	(
        ///		select Count(id) as RfProses from candidate 
        ///		where  permanentagentcode is null and Status!=&apos;REJECT&apos; and IsDeleted != 1 AND RecruiterAgentCode=@RecruiterAgentCode and Month(submitdate [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GetDashboardActivitySummaryPerMonth {
            get {
                return ResourceManager.GetString("GetDashboardActivitySummaryPerMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select TblSubmit.RfSubmit, TblProses.RfProses, TblActive.AgentActivated
        ///	from(
        ///		--sudah submit
        ///		select Count(id) as RfSubmit from candidate 
        ///		where SubmitDate is not NULL AND IsDeleted != 1 AND RecruiterAgentCode=@RecruiterAgentCode and Month(submitdate) = @Month and Year(submitdate) = @Year
        ///
        ///	) as TblSubmit,
        ///	(
        ///		select Count(id) as RfProses from candidate 
        ///		where  permanentagentcode is null and Status!=&apos;REJECT&apos; and IsDeleted != 1 AND RecruiterAgentCode=@RecruiterAgentCode and Month(submitdate [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GetDashboardActivitySummaryPerMonthMobile {
            get {
                return ResourceManager.GetString("GetDashboardActivitySummaryPerMonthMobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT * FROM (
        ///select 
        ///	ROW_NUMBER() OVER(ORDER BY c.Name asc) AS NUMBER,
        ///	c.Id,
        ///	c.Name, 
        ///	r.RoleName,
        ///	c.ChangedWhen as LastUpdate,
        ///	case when SubmitDate IS NULL then &apos;Pengisian RF&apos; 
        ///		when AllLeaderApproveFlag = 0 then &apos;Menunggu Persetujuan&apos; 
        ///		when DocumentCheckingFlag = 0 Then &apos;Menunggu Proses Dokumen Cek&apos; 
        ///		when ElearningPassedFlag = 0 then &apos;Menunggu Hasil Elearning&apos; 
        ///		when AajiPassedFlag = 0 then &apos;Menunggu Hasil Ujian AAJI&apos;
        ///		when submitdate is not null and AllLeaderApproveFlag=1 and D [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GetDashboardListCandidateProses {
            get {
                return ResourceManager.GetString("GetDashboardListCandidateProses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT * FROM (
        ///select 
        ///	ROW_NUMBER() OVER(ORDER BY c.Name asc) AS NUMBER,
        ///	c.Id,
        ///	c.Name, 
        ///	r.RoleName,
        ///	c.ChangedWhen as LastUpdate,
        ///	case when SubmitDate IS NULL then &apos;Pengisian RF&apos; 
        ///		when AllLeaderApproveFlag = 0 then &apos;Menunggu Persetujuan&apos; 
        ///		when DocumentCheckingFlag = 0 Then &apos;Menunggu Proses Dokumen Cek&apos; 
        ///		when ElearningPassedFlag = 0 then &apos;Menunggu Hasil Elearning&apos; 
        ///		when AajiPassedFlag = 0 then &apos;Menunggu Hasil Ujian AAJI&apos;
        ///		when submitdate is not null and AllLeaderApproveFlag=1 and D [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GetDashboardListCandidateProsesMobile {
            get {
                return ResourceManager.GetString("GetDashboardListCandidateProsesMobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select C.TemporaryAgentCode, C.Name, r.RoleName Level, tim.TeamName, loc.AgentLocation Location, dm.DisplayName Manager, 
        ///rec.DisplayName RecruiterName, FU.Path Photo
        ///from Candidate C
        ///left join [Role] r ON c.Level = r.ID
        ///left join Account rec ON c.RecruiterAgentCode = rec.AgentCode
        ///left join Team tim ON rec.TeamCode = tim.TeamCode
        ///left join Location loc ON c.LocationCode = loc.AgentLocationCode
        ///left join Account dm ON C.DirectManagerCode = dm.AgentCode
        ///left join CandidateFile CF ON C.ID = CF.Candida [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GetDetailApproval {
            get {
                return ResourceManager.GetString("GetDetailApproval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT c.GroupLevel FROM Candidate c where c.ID = @CandidateId.
        /// </summary>
        internal static string GetGroupByCandidate {
            get {
                return ResourceManager.GetString("GetGroupByCandidate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT * FROM (
        ///	SELECT ROW_NUMBER() OVER(ORDER BY i.id desc) AS NUMBER, i.*, al.Reason,
        ///		(
        ///			SELECT COUNT(*) FROM Inbox where (ToMail like @ToMail or @ToMail is null)
        ///		) [Length]
        ///	FROM Inbox i 
        ///	left join ApprovalList al on i.ForeignKey = al.ID
        ///	WHERE (ToMail like @ToMail or @ToMail is null) 
        ///) AS TBL
        ///WHERE NUMBER BETWEEN ((@PageNumber - 1) * @RowsPage + 1) AND (@PageNumber * @RowsPage)
        ///ORDER BY NUMBER.
        /// </summary>
        internal static string GetInbox {
            get {
                return ResourceManager.GetString("GetInbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select * FROM Inbox
        ///WHERE (ToMail like @ToMail or @ToMail is null)
        ///order by id desc.
        /// </summary>
        internal static string GetInboxMobile {
            get {
                return ResourceManager.GetString("GetInboxMobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT a.*, re.DisplayName RecruiterName, b.Name, r.RoleName as &apos;Level&apos;, loc.AgentLocation Location, b.Status CandidateStatus
        ///FROM ApprovalList a
        ///JOIN Candidate b ON a.CandidateId = b.ID
        ///LEFT JOIN Location loc on loc.AgentLocationCode = b.LocationCode
        ///LEFT JOIN Account re ON a.RecruiterCode = re.AgentCode
        ///LEFT JOIN Account ap ON a.ApproverCode = ap.AgentCode
        ///LEFT JOIN [Role] r on b.Level = r.ID
        ///LEFT JOIN CandidateFile CF ON CF.CandidateID = b.ID AND CF.Type = &apos;FotoDiri&apos;
        ///LEFT JOIN FileUpload FU ON CF [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GetListApproval {
            get {
                return ResourceManager.GetString("GetListApproval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT * FROM (
        ///	SELECT ROW_NUMBER() OVER(ORDER BY a.ID desc) AS NUMBER,a.ID, a.CandidateId, a.RecruiterCode, a.ApproverCode, re.DisplayName RecruiterName, b.Name, r.RoleName as &apos;Level&apos;, 
        ///	loc.AgentLocation Location, b.Status CandidateStatus, FU.Path Photo,
        ///		(
        ///			SELECT COUNT(*)
        ///			FROM ApprovalList a 
        ///			JOIN Candidate b ON a.CandidateId = b.ID
        ///			LEFT JOIN Location loc on loc.AgentLocationCode = b.LocationCode
        ///			LEFT JOIN Account re ON a.RecruiterCode = re.AgentCode
        ///			--LEFT JOIN Account ap ON [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GetListApprovalWeb {
            get {
                return ResourceManager.GetString("GetListApprovalWeb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT * FROM (
        ///	SELECT ROW_NUMBER() OVER(ORDER BY el.id) AS NUMBER,
        ///		el.Id,
        ///		el.Name,c.Id as CityId,
        ///		el.CityCode,
        ///		c.Name as CityName,
        ///		el.ExamType,
        ///		el.IsActive,
        ///		(
        ///			SELECT COUNT(*)
        ///			FROM ExamLocation ell
        ///			join City cc on ell.CityCode = cc.CityCode
        ///			WHERE 
        ///				(ell.[Name] like @Name or @Name is null)
        ///				AND (C.Name like @CityName or @CityName is null)
        ///				AND (ExamType like @ExamType or @ExamType is null)
        ///				AND c.IsDelete != 1
        ///		) [Length]
        ///	FROM ExamLocation el
        ///	join  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GetListExamLocation {
            get {
                return ResourceManager.GetString("GetListExamLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select el.Id,
        ///el.Name,c.Id as CityId,
        ///el.CityCode,
        ///c.Name as CityName,
        ///el.ExamType,
        ///el.IsActive
        ///FROM ExamLocation el join City c on c.CityCode = el.CityCode
        ///where el.IsDelete != 1 AND ExamType = @ExamType.
        /// </summary>
        internal static string GetListExamLocationMobile {
            get {
                return ResourceManager.GetString("GetListExamLocationMobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select id from CandidateDependencies where CandidateId = @CandidateId.
        /// </summary>
        internal static string GetListIdCandidateDependencies {
            get {
                return ResourceManager.GetString("GetListIdCandidateDependencies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select id from candidateeducation where candidateid = @CandidateId.
        /// </summary>
        internal static string GetListIdCandidateEducation {
            get {
                return ResourceManager.GetString("GetListIdCandidateEducation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select id from candidateexperience where candidateid = @CandidateId.
        /// </summary>
        internal static string GetListIdCandidateExperience {
            get {
                return ResourceManager.GetString("GetListIdCandidateExperience", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select id from CandidateReference where CandidateID = @CandidateId.
        /// </summary>
        internal static string GetListIdCandidateReference {
            get {
                return ResourceManager.GetString("GetListIdCandidateReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select id from CandidateRelationInInsurance where CandidateID = @CandidateId.
        /// </summary>
        internal static string GetListIdCandidateRelationInInsurance {
            get {
                return ResourceManager.GetString("GetListIdCandidateRelationInInsurance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select id from CandidateWorkExperienceInInsurance where CandidateID = @CandidateId.
        /// </summary>
        internal static string GetListIdCandidateWorkExperienceInInsurance {
            get {
                return ResourceManager.GetString("GetListIdCandidateWorkExperienceInInsurance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select * from Location where IsDelete != 1 order by AgentLocation asc.
        /// </summary>
        internal static string GetLocation {
            get {
                return ResourceManager.GetString("GetLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select l.ID, l.AgentLocationCode 
        ///from Candidate c 
        ///join Location l on c.Location = l.ID
        ///where c.ID = @CandidateId.
        /// </summary>
        internal static string GetLocationByCandidate {
            get {
                return ResourceManager.GetString("GetLocationByCandidate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select * from Location where IsDelete != 1.
        /// </summary>
        internal static string GetLocationMobile {
            get {
                return ResourceManager.GetString("GetLocationMobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT LoginName FROM ForgotPassword WHERE Link = @link.
        /// </summary>
        internal static string GetLoginNameFromForgot {
            get {
                return ResourceManager.GetString("GetLoginNameFromForgot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to exec GetManager @RecruiterLoginName, @CandidateRoleId.
        /// </summary>
        internal static string GetManager {
            get {
                return ResourceManager.GetString("GetManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to exec GetManager @RecruiterLoginName, @CandidateRoleId.
        /// </summary>
        internal static string GetManagerMobile {
            get {
                return ResourceManager.GetString("GetManagerMobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select top 1 Reason from DocumentCheck where CandidateId=@CandidateId order by id desc.
        /// </summary>
        internal static string GetNotifPendingDocument {
            get {
                return ResourceManager.GetString("GetNotifPendingDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select C.ID,C.[Name], C.JoinDate,[DC].[Status], DC.Reason,F.Path as Photo
        ///from DocumentCheck DC 
        ///join Candidate C on DC.CandidateId = C.ID
        ///join Account A on C.RecruiterAgentCode = A.AgentCode
        ///left join CandidateFile CF on CF.CandidateID = C.ID and CF.Type = &apos;FotoDiri&apos;
        ///left join FileUpload F on F.ID = CF.FileID
        ///where A.LoginName = @LoginName and DC.Status = &apos;NEED REVISION&apos;
        ///order by c.ChangedWhen desc.
        /// </summary>
        internal static string GetPendingDocument {
            get {
                return ResourceManager.GetString("GetPendingDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select C.ID,C.[Name], C.JoinDate,[DC].[Status], DC.Reason,F.Path as Photo
        ///from DocumentCheck DC 
        ///join Candidate C on DC.CandidateId = C.ID
        ///join Account A on C.RecruiterAgentCode = A.AgentCode
        ///left join CandidateFile CF on CF.CandidateID = C.ID and CF.Type = &apos;FotoDiri&apos;
        ///left join FileUpload F on F.ID = CF.FileID
        ///where A.LoginName = @LoginName and DC.Status = &apos;NEED REVISION&apos;
        ///order by c.ChangedWhen desc.
        /// </summary>
        internal static string GetPendingDocumentMobile {
            get {
                return ResourceManager.GetString("GetPendingDocumentMobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select top 1 TotalScore  
        ///from CandidateProfilingHeader
        ///where CandidateID=@CandidateId
        ///order by TotalScore desc.
        /// </summary>
        internal static string GetProfillingHeaderScore {
            get {
                return ResourceManager.GetString("GetProfillingHeaderScore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select Id,Gender, MaritalStatus, Dependencies, PTKPStatus, PTKPPerMonth, PTKPPeryear
        ///from PTKP.
        /// </summary>
        internal static string GetPTKP {
            get {
                return ResourceManager.GetString("GetPTKP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select Id,Gender, MaritalStatus, Dependencies, PTKPStatus, PTKPPerMonth, PTKPPeryear
        ///from PTKP.
        /// </summary>
        internal static string GetPTKPMobile {
            get {
                return ResourceManager.GetString("GetPTKPMobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT ROW_NUMBER() OVER(ORDER BY P.ID) AS Number, P.* FROM ProfilingQuestion P WHERE IsActive = 1 AND IsDelete = 0 AND GroupID = @GroupID.
        /// </summary>
        internal static string GetQuestion {
            get {
                return ResourceManager.GetString("GetQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT ROW_NUMBER() OVER(ORDER BY P.ID) AS Number, P.* FROM ProfilingQuestion P WHERE IsActive = 1 AND IsDelete = 0.
        /// </summary>
        internal static string GetQuestionMobile {
            get {
                return ResourceManager.GetString("GetQuestionMobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select A.ID as id, ExamDate,CONVERT(varchar(10), Year(ExamDate)) + &apos;/&apos; + CONVERT(varchar(10), Month(ExamDate))+ &apos;/&apos; +CONVERT(varchar(10), Day(ExamDate))  as [start], RegisteredUser,c.ID AS CityId,C.[Name] as CityName,EL.ID as ExamLocationId, EL.[Name] as ExamLocationName,A.Note, A.Note as title, EL.ExamType
        ///from AajiExam A
        ///left join ExamLocation EL on A.ExamLocationId = EL.ID
        ///left join City C on EL.CityCode = C.CityCode
        ///where ( ExamDate Between getdate() and DATEADD(month,3,GETDATE()))  and A.IsDelete ! [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GetScheduleAajiExam {
            get {
                return ResourceManager.GetString("GetScheduleAajiExam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select A.ID as id, ExamDate,CONVERT(varchar(10), Year(ExamDate)) + &apos;/&apos; + CONVERT(varchar(10), Month(ExamDate))+ &apos;/&apos; +CONVERT(varchar(10), Day(ExamDate))  as [start], RegisteredUser,c.ID AS CityId,C.[Name] as CityName,EL.ID as ExamLocationId, EL.[Name] as ExamLocationName,A.Note, A.Note as title, EL.ExamType
        ///from AajiExam A
        ///left join ExamLocation EL on A.ExamLocationId = EL.ID
        ///left join City C on EL.CityCode = C.CityCode
        ///where ( ExamDate Between getdate() and DATEADD(month,3,GETDATE()))  and A.IsDelete ! [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GetScheduleAajiExamMobile {
            get {
                return ResourceManager.GetString("GetScheduleAajiExamMobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select A.ID as id, ExamDate,CONVERT(varchar(10), Year(ExamDate)) + &apos;/&apos; + CONVERT(varchar(10), Month(ExamDate))+ &apos;/&apos; +CONVERT(varchar(10), Day(ExamDate))  as [start], RegisteredUser,c.ID AS CityId,C.[Name] as CityName,EL.ID as ExamLocationId, EL.[Name] as ExamLocationName,A.Note, A.Note as title, EL.ExamType
        ///from AajiExam A
        ///join ExamLocation EL on A.ExamLocationId = EL.ID
        ///join City C on EL.CityCode = C.CityCode
        ///where Year(A.ExamDate) = @Year and A.IsDelete != 1 and el.CityCode = c.CityCode AND C.ID = @Ci [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GetScheduleAajiExamold {
            get {
                return ResourceManager.GetString("GetScheduleAajiExamold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT T.Syariah FROM Candidate C
        ///JOIN Account A ON C.RecruiterAgentCode = A.AgentCode
        ///JOIN Team T ON A.TeamCode = T.TeamCode
        ///WHERE C.ID = @CandidateId.
        /// </summary>
        internal static string GetSyariahFlagByCandidateId {
            get {
                return ResourceManager.GetString("GetSyariahFlagByCandidateId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select top 1 acc.Loginname, acc.[Password], acc.Displayname, acc.Email,acc.IsActive,  acc.RoleId, rol.RoleName, 
        ///acc.AgentCode, acc.PhoneNo,c.Photo
        ///from account acc 
        ///join role rol on acc.RoleID = rol.id
        ///left join Candidate c on c.AgentCode = acc.AgentCode
        ///where acc.loginname=@loginName.
        /// </summary>
        internal static string GetUser {
            get {
                return ResourceManager.GetString("GetUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select top 1 acc.Loginname, acc.[Password], acc.Displayname, acc.Email, acc.RoleId, rol.RoleName, 
        ///acc.AgentCode, acc.PhoneNo,c.Photo
        ///from account acc 
        ///join role rol on acc.RoleID = rol.id
        ///left join Candidate c on c.AgentCode = acc.AgentCode
        ///where acc.AgentCode=@AgentCode.
        /// </summary>
        internal static string GetUserMobile {
            get {
                return ResourceManager.GetString("GetUserMobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT F.Path FROM Candidate C JOIN FileUpload F ON C.Photo = F.ID
        ///WHERE C.ID = @ID.
        /// </summary>
        internal static string GetUserPhoto {
            get {
                return ResourceManager.GetString("GetUserPhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT Value FROM GlobalConfiguration WHERE Keyword = @Keyword.
        /// </summary>
        internal static string GetValueGlobalConfiguration {
            get {
                return ResourceManager.GetString("GetValueGlobalConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE ApprovalList SET StatusApproval = @StatusApproval,
        ///Reason = @Reason, ApprovalDate = @ApprovalDate WHERE ID = @ID.
        /// </summary>
        internal static string SetApprovalAction {
            get {
                return ResourceManager.GetString("SetApprovalAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT tipe.TypeID BusinessTypeId, business.Name BusinessTypeName, acc2.*
        ///FROM eLearning.dbo.Account acc1
        ///join eRecruit.dbo.Account acc2
        ///ON acc1.LoginName = acc2.LoginName
        ///JOIN eLearning.dbo.LearningType tipe ON acc1.TypeID = tipe.ID
        ///JOIN eLearning.dbo.BusinessType business ON tipe.TypeID = business.ID.
        /// </summary>
        internal static string Testing {
            get {
                return ResourceManager.GetString("Testing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to declare @LocationId int = (select location from Candidate where id = @CandidateId )
        ///update Location 
        ///set AgentLocation=&apos;test&apos;
        ///where id = @LocationId;
        ///select @LocationId as locationid.
        /// </summary>
        internal static string UpdateCandidateLocation {
            get {
                return ResourceManager.GetString("UpdateCandidateLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE CandidateProfilingAnswer SET Answer = @Answer, Point = @Point, Description = @Description
        ///WHERE HeaderID = @HeaderID AND QuestionID = @QuestionID.
        /// </summary>
        internal static string UpdateCandidateProfilingAnswer {
            get {
                return ResourceManager.GetString("UpdateCandidateProfilingAnswer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE Inbox SET IsRead = 1 WHERE ID = @ID.
        /// </summary>
        internal static string UpdateIsReadInbox {
            get {
                return ResourceManager.GetString("UpdateIsReadInbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE Candidate SET Photo = @PhotoId WHERE ID = @ID.
        /// </summary>
        internal static string UpdateUserPhoto {
            get {
                return ResourceManager.GetString("UpdateUserPhoto", resourceCulture);
            }
        }
    }
}
