CREATE TABLE [dbo].[Agama](
	[ID] [bigint] NOT NULL,
	[Agama] [varchar](30) NULL,
	[IDAgama] [varchar](10) NULL,
 CONSTRAINT [PK_Agama] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

