CREATE TABLE [dbo].[Candidate] (
    [ID]                      BIGINT         IDENTITY (1, 1) NOT NULL,
    [Photo]                   VARCHAR (MAX)  NULL,
    [Name]                    VARCHAR (100)  NULL,
    [Email]                   VARCHAR (100)  NULL,
    [KTPNo]                   VARCHAR (50)   NULL,
    [CurrentAddress]          VARCHAR (200)  NULL,
    [City]                    VARCHAR (50)   NULL,
    [PostalCode]              VARCHAR (10)   NULL,
    [Gender]                  VARCHAR (1)    NULL,
    [PhoneNo]                 VARCHAR (50)   NULL,
    [MaritalStatus]           VARCHAR (50)   NULL,
    [BirthDate]               DATETIME       NULL,
    [Religion]                VARCHAR (50)   NULL,
    [BankAccountName]         VARCHAR (50)   NULL,
    [BankAccountNo]           VARCHAR (50)   NULL,
    [Branch]                  VARCHAR (50)   NULL,
    [NPWPName]                VARCHAR (100)  NULL,
    [NPWPNo]                  VARCHAR (50)   NULL,
    [AgentCode]               VARCHAR (50)   NULL,
    [TemporaryAgentCode]      VARCHAR (50)   NULL,
    [PermanentAgentCode]      VARCHAR (50)   NULL,
    [RecruiterAgentCode]      VARCHAR (50)   NULL,
    [DirectManagerCode]       VARCHAR (50)   NULL,
    [AAJIResultFile]          VARCHAR (500)  NULL,
    [AAJISchedule]            DATETIME       NULL,
    [CandidateSignature]      VARCHAR (MAX)  NULL,
    [RecruiterSignature]      VARCHAR (MAX)  NULL,
    [Profession]              VARCHAR (50)   NULL,
    [IsDeleted]               BIT            NULL,
    [JoinDate]                DATE           NULL,
    [HomeAddress]             VARCHAR (200)  NULL,
    [Level]                   INT            NULL,
    [Status]                  VARCHAR (50)   NULL,
    [Location]                INT            NULL,
    [DocumentCheckingFlag]    BIT            CONSTRAINT [DF_Candidate_DocumentCheckingFlag] DEFAULT ((0)) NULL,
    [AllLeaderApproveFlag]    BIT            CONSTRAINT [DF_Candidate_AllLeaderApproveFlag] DEFAULT ((0)) NULL,
    [AajiPassedFlag]          BIT            CONSTRAINT [DF_Candidate_AajiPassedFlag] DEFAULT ((0)) NULL,
    [ELearningPassedFlag]     BIT            CONSTRAINT [DF_Candidate_ELearningPassedFlag] DEFAULT ((0)) NULL,
    [GroupLevel]              INT            NULL,
    [BankCode]                NVARCHAR (20)  NULL,
    [SpouseName]              NVARCHAR (100) NULL,
    [SpouseBirthDate]         DATETIME       NULL,
    [PropertyOwnershipStatus] NVARCHAR (50)  NULL,
    [BirthPlace]              NVARCHAR (100) NULL,
    [HomePhone]               NVARCHAR (50)  NULL,
    [Income]                  BIGINT         NULL,
    [NPWPRelationWith]        VARCHAR (50)   NULL,
    [CurrentCityId]           INT            NULL,
    [CurrentCityCode]         VARCHAR (50)   NULL,
    [CurrentPostalCode]       VARCHAR (10)   NULL,
    [PTKPHeader]              NVARCHAR (100) NULL,
    [PTKPDetail]              INT            NULL,
    [CityCode]                VARCHAR (50)   NULL,
    [SubmitDate]              DATETIME       NULL,
    [CreatedWhen]             DATETIME       NULL,
    [CreatedBy]               VARCHAR (100)  NULL,
    [ChangedWhen]             DATETIME       NULL,
    [ChangedBy]               VARCHAR (100)  NULL,
    [ActiveDate]              DATETIME       NULL,
    [LocationCode]            NVARCHAR (50)  NULL,
    [VirtualAccount]          NCHAR (50)     NULL,
    [IDFromMobile]            VARCHAR (15)   NULL,
    [AgentDirectorLocation]   VARCHAR (250)  NULL,
    [ElearningPassedDate]     NVARCHAR (50)  NULL,
    [UpdateResubmitDate]      DATETIME       NULL,
    [RT] VARCHAR(3) NULL, 
    [RW] VARCHAR(3) NULL, 
    [Province] VARCHAR(10) NULL, 
    [LoginName] VARCHAR(10) NULL, 
    CONSTRAINT [PK_Candidate] PRIMARY KEY CLUSTERED ([ID] ASC)
);

