
CREATE PROCEDURE [dbo].[Update_ApprovalHierarki]
      @TBLACCOUNT APPROVALHIERARKITYPE READONLY
AS
BEGIN
      SET NOCOUNT ON;

      MERGE INTO APPROVALHIERARKI C1
      USING @TBLACCOUNT C2
     ON (C1.AGENTCODE = C2.AGENTCODE AND C1.LEVELID = C2.LEVELID)
      WHEN MATCHED THEN
		UPDATE SET C1.ISACTIVE = C2.ISACTIVE,
            C1.ISDELETE = C2.ISDELETE,
			C1.APPROVERCODE = C2.APPROVERCODE,
			C1.SEQUENCE = C2.SEQUENCE
      WHEN NOT MATCHED BY TARGET THEN
		INSERT VALUES (C2.AGENTCODE, C2.APPROVERCODE, C2.LEVELID, C2.ISACTIVE, C2.ISDELETE, C2.SEQUENCE)
	  WHEN NOT MATCHED BY SOURCE AND (c1.AgentCode in (select AgentCode from @TBLACCOUNT)) and c1.LevelId not in (select LevelId from @TBLACCOUNT where AgentCode = c1.AgentCode) THEN
	  DELETE;
END


--use erecruitment
--select * from ApprovalHierarki where AgentCode in ('A00024') AND levelid not in (3)
-- AND ApproverCode NOT IN ('S22459')

--SELECT COUNT(*) from ApprovalHierarki