
CREATE PROCEDURE [dbo].[UPDATE_APPROVALHIERARKIMANAGEMENT]
      @TBLACCOUNT [APPROVALHIERARKIMANAGEMENTTYPE] READONLY
AS
BEGIN
      SET NOCOUNT ON;
 
      MERGE INTO APPROVALHIERARKIMANAGEMENT C1
      USING @TBLACCOUNT C2
      ON 
			--C1.APPROVECODE = C2.APPROVECODE and
			C1.LOCATIONCODE= C2.LOCATIONCODE and
			C1.LEVELID = C2.LEVELID 
      WHEN MATCHED THEN
      UPDATE SET C1.ISACTIVE = C2.ISACTIVE,
            C1.ISDELETE = C2.ISDELETE,
			C1.APPROVECODE = C2.APPROVECODE,
			C1.LOCATIONCODE= C2.LOCATIONCODE,
			C1.LEVELID = C2.LEVELID,
			C1.SEQUENCE = C2.SEQUENCE
      WHEN NOT MATCHED BY TARGET THEN
       INSERT VALUES (C2.LOCATIONCODE,C2.APPROVECODE, C2.LEVELID, C2.ISACTIVE, C2.ISDELETE, C2.SEQUENCE)
	  WHEN NOT MATCHED BY SOURCE AND (c1.LocationCode in (select LocationCode from @TBLACCOUNT))
	  --and c1.ApproveCode not in (select ApproveCode from @TBLACCOUNT where LocationCode = c1.LocationCode)) 
	  THEN
	  DELETE;
END
